export const cars = [
  {
    id: 1,
    image: '',
    brand: 'Tesla',
    model: 'Model S',
    color: 'White',
    price: 79999,
    year: 2021,
    engineType: 'Electric',
    range: 400,
  },
  {
    id: 2,
    image: '',
    brand: 'BMW',
    model: 'X5',
    color: 'Black',
    price: 59999,
    year: 2019,
    engineType: 'Diesel',
    transmission: 'Automatic',
  },
  {
    id: 3,
    image: '',
    brand: 'Toyota',
    model: 'Camry',
    color: 'Silver',
    price: 24999,
    year: 2020,
    engineType: 'Gasoline',
    transmission: 'Automatic',
  },
  {
    id: 4,
    image:
      'https://avatars.mds.yandex.net/get-autoru-vos/6027420/2fdc6acb5c1359f7c54ff7ba87631d89/1200x900',
    brand: 'Ford',
    model: 'Mustang',
    color: 'Red',
    price: 34999,
    year: 2018,
    engineType: 'Gasoline',
    transmission: 'Manual',
  },
  {
    id: 5,
    image: '',
    brand: 'Hyundai',
    model: 'Kona',
    color: 'Blue',
    price: 19999,
    year: 2022,
    engineType: 'Electric',
    range: 250,
  },
  {
    id: 6,
    image: '',
    brand: 'BMW',
    model: 'X6',
    color: 'Black',
    price: 69999,
    year: 2019,
    engineType: 'Diesel',
    transmission: 'Automatic',
  },
  {
    id: 7,
    image: '',
    brand: 'Audi',
    model: 'A4',
    color: 'Gray',
    price: 32999,
    year: 2019,
    engineType: 'Gasoline',
    transmission: 'Automatic',
  },
  {
    id: 8,
    image: '',
    brand: 'Mercedes-Benz',
    model: 'C-Class',
    color: 'Black',
    price: 35999,
    year: 2020,
    engineType: 'Gasoline',
    transmission: 'Automatic',
  },
  {
    id: 9,
    image: '',
    brand: 'Volkswagen',
    model: 'Golf',
    color: 'White',
    price: 19999,
    year: 2018,
    engineType: 'Gasoline',
    transmission: 'Manual',
  },
  {
    id: 10,
    image: '',
    brand: 'Chevrolet',
    model: 'Bolt EV',
    color: 'Blue',
    price: 36999,
    year: 2021,
    engineType: 'Electric',
    range: 259,
  },
  {
    id: 11,
    image: '',
    brand: 'Nissan',
    model: 'Leaf',
    color: 'Green',
    price: 28999,
    year: 2020,
    engineType: 'Electric',
    range: 226,
  },
  {
    id: 12,
    image: '',
    brand: 'Honda',
    model: 'Civic',
    color: 'Silver',
    price: 21999,
    year: 2019,
    engineType: 'Gasoline',
    transmission: 'Automatic',
  },
  {
    id: 13,
    image: '',
    brand: 'Toyota',
    model: 'Prius',
    color: 'White',
    price: 24999,
    year: 2020,
    engineType: 'Diesel',
    transmission: 'Automatic',
  },
  {
    id: 14,
    image: '',
    brand: 'Ford',
    model: 'F-150',
    color: 'Black',
    price: 39999,
    year: 2021,
    engineType: 'Gasoline',
    transmission: 'Automatic',
  },
  {
    id: 15,
    image: '',
    brand: 'Kia',
    model: 'Soul EV',
    color: 'Red',
    price: 33999,
    year: 2020,
    engineType: 'Electric',
    range: 243,
  },
  {
    id: 16,
    image: '',
    brand: 'Tesla',
    model: 'Model 3',
    color: 'White',
    price: 37999,
    year: 2021,
    engineType: 'Electric',
    range: 353,
  },
  {
    id: 17,
    image: '',
    brand: 'BMW',
    model: 'i3',
    color: 'Gray',
    price: 44999,
    year: 2019,
    engineType: 'Electric',
    range: 153,
  },
  {
    id: 18,
    image: '',
    brand: 'Chevrolet',
    model: 'Camaro',
    color: 'Yellow',
    price: 25999,
    year: 2018,
    engineType: 'Gasoline',
    transmission: 'Manual',
  },
  {
    id: 19,
    image: '',
    brand: 'Audi',
    model: 'Q7',
    color: 'Blue',
    price: 54999,
    year: 2020,
    engineType: 'Diesel',
    transmission: 'Automatic',
  },
  {
    id: 20,
    image: '',
    brand: 'Mercedes-Benz',
    model: 'GLE',
    color: 'Silver',
    price: 59999,
    year: 2021,
    engineType: 'Gasoline',
    transmission: 'Automatic',
  },
  {
    id: 21,
    image: '',
    brand: 'Jaguar',
    model: 'I-PACE',
    color: 'Black',
    price: 69999,
    year: 2020,
    engineType: 'Electric',
    range: 234,
  },
  {
    id: 22,
    image: '',
    brand: 'Hyundai',
    model: 'Ioniq Electric',
    color: 'White',
    price: 30999,
    year: 2019,
    engineType: 'Electric',
    range: 170,
  },
  {
    id: 23,
    image: '',
    brand: 'Porsche',
    model: 'Taycan',
    color: 'Red',
    price: 104999,
    year: 2021,
    engineType: 'Electric',
    range: 227,
  },
  {
    id: 24,
    image: '',
    brand: 'Volvo',
    model: 'XC90',
    color: 'Gray',
    price: 45999,
    year: 2018,
    engineType: 'Diesel',
    transmission: 'Automatic',
  },
  {
    id: 25,
    image: '',
    brand: 'Mazda',
    model: 'CX-5',
    color: 'Blue',
    price: 27999,
    year: 2019,
    engineType: 'Gasoline',
    transmission: 'Automatic',
  },
  {
    id: 26,
    image: '',
    brand: 'Lexus',
    model: 'RX 350',
    color: 'Silver',
    price: 41999,
    year: 2020,
    engineType: 'Gasoline',
    transmission: 'Automatic',
  },
  {
    id: 27,
    image: '',
    brand: 'Subaru',
    model: 'Outback',
    color: 'Green',
    price: 24999,
    year: 2018,
    engineType: 'Gasoline',
    transmission: 'Automatic',
  },
  {
    id: 28,
    image: '',
    brand: 'Nissan',
    model: 'Altima',
    color: 'Black',
    price: 22999,
    year: 2019,
    engineType: 'Gasoline',
    transmission: 'Automatic',
  },
  {
    id: 29,
    image: '',
    brand: 'Tesla',
    model: 'Model X',
    color: 'White',
    price: 89999,
    year: 2021,
    engineType: 'Electric',
    range: 360,
  },
  {
    id: 30,
    image: '',
    brand: 'Chevrolet',
    model: 'Silverado',
    color: 'Red',
    price: 35999,
    year: 2020,
    engineType: 'Gasoline',
    transmission: 'Automatic',
  },
  {
    id: 31,
    image: '',
    brand: 'Ford',
    model: 'Explorer',
    color: 'Blue',
    price: 32999,
    year: 2019,
    engineType: 'Gasoline',
    transmission: 'Automatic',
  },
  {
    id: 32,
    image: '',
    brand: 'Jeep',
    model: 'Wrangler',
    color: 'Green',
    price: 28999,
    year: 2018,
    engineType: 'Gasoline',
    transmission: 'Manual',
  },
  {
    id: 33,
    image: '',
    brand: 'Toyota',
    model: 'Corolla',
    color: 'Silver',
    price: 19999,
    year: 2020,
    engineType: 'Gasoline',
    transmission: 'Automatic',
  },
  {
    id: 34,
    image: '',
    brand: 'Honda',
    model: 'Accord',
    color: 'Black',
    price: 24999,
    year: 2019,
    engineType: 'Gasoline',
    transmission: 'Automatic',
  },
  {
    id: 35,
    image: '',
    brand: 'Volkswagen',
    model: 'Passat',
    color: 'White',
    price: 21999,
    year: 2018,
    engineType: 'Diesel',
    transmission: 'Automatic',
  },
  {
    id: 36,
    image: '',
    brand: 'BMW',
    model: '5 Series',
    color: 'Gray',
    price: 49999,
    year: 2020,
    engineType: 'Gasoline',
    transmission: 'Automatic',
  },
  {
    id: 37,
    image: '',
    brand: 'Audi',
    model: 'e-tron',
    color: 'Blue',
    price: 65999,
    year: 2021,
    engineType: 'Electric',
    range: 222,
  },
  {
    id: 38,
    image: '',
    brand: 'Kia',
    model: 'Niro EV',
    color: 'White',
    price: 38999,
    year: 2020,
    engineType: 'Electric',
    range: 239,
  },
  {
    id: 39,
    image: '',
    brand: 'Hyundai',
    model: 'Tucson',
    color: 'Silver',
    price: 22999,
    year: 2019,
    engineType: 'Gasoline',
    transmission: 'Automatic',
  },
  {
    id: 40,
    image: '',
    brand: 'Porsche',
    model: 'Cayenne',
    color: 'Black',
    price: 74999,
    year: 2020,
    engineType: 'Gasoline',
    transmission: 'Automatic',
  },
  {
    id: 41,
    image: '',
    brand: 'Land Rover',
    model: 'Range Rover',
    color: 'Green',
    price: 89999,
    year: 2021,
    engineType: 'Diesel',
    transmission: 'Automatic',
  },
];
